### PR TITLE
Refactored types into a more organized hierarchy.

### PR DESCRIPTION
**Pull request by cjbeery24**
# Fixes: #109 

## Description

Refactored types into a more organized hierarchy.

## Changes

- Organized typescript types

## PR Tasks

- [x] Open PR
- [x] run `npm run test` --> no failing unit tests
- [x] run `npm run format`

### CODE REVIEW

**Comment by Egge21M** [comment]
I like this alot. Thank you for doing this.

However I think after merging this we need to take this even further for a later major release. As pointed out in https://github.com/cashubtc/cashu-ts/issues/109 some Types are not unambiguous enough. Also thinks like `SendResponse` (which is not a response) should be renamed IMO.

We can still proceed with merging this change though, to clean things up a little

**Review by Egge21M — APPROVED** [review]
LGTM

**Review by callebtc — APPROVED** [review]
utACK, you're doing satoshis work 🙏

**Comment by Egge21M** [comment]
@cjbeery24 could you please rebase this PR to the `development` branch? I would love to include this with the next release

**Comment by cjbeery24** [comment]
@Egge21M Okay, think I did that correctly.

**Pull request merged**
