### PR TITLE
V1 api

### PR DESCRIPTION
**Pull request by callebtc**
Updates to the V1 API in Cashu-TS. 

Todo:
- [x] Implement all v1 endpoints and models
  - [x] `GET /v1/info`
  - [x] `GET /v1/keys`
  - [x] `GET /v1/keys/{keyset_id}`
  - [x] `GET /v1/keysets`
  - [x] `GET /v1/check`
  - [x] `POST /v1/split`
  - [x] `POST /v1/melt/quote/bolt11`
  - [x] `POST /v1/melt/bolt11`
  - [x] `POST /v1/mint/quote/bolt11`
  - [x] `POST /v1/mint/bolt11`
- [x] `BlindedMessage` now has `id` field
- [x] Use 64-char hex string for generating secrets
- [x] Update tests to new hex keyset IDs and secrets
- [x] Add Nutshell mint end-to-end integration tests (Docker pipeline not working yet, but tests are green)

Out of scope: 
Implement keyset ID derivation. Right now, it simply trusts the mint to respond with the correct keyset ID

### CODE REVIEW

**Review by gandlafbtc — DISMISSED** [review]
LGTM!

I would like to do some manual testing before merge

**Comment by starbackr-dev** [comment]
This PR still lacks passing the unit='usd' to getMintQuote. Do you want to update after v1 is merged?

**Comment by gandlafbtc** [comment]
yes

**Comment by starbackr-dev** [comment]
Still waiting for this to get merged into dev branch before I can make changes for unit=usd.

**Comment by callebtc** [comment]
I'm going to one more thing before the merge: https://github.com/cashubtc/nuts/pull/93

**Comment by gandlafbtc** [comment]
I was doing some more reviewing and there will be some more changes coming.

**Comment by gandlafbtc** [comment]
I think this is ready for merge. Did more testing with nutstash wallet, and everything seems to work as expected. @callebtc

**Comment by callebtc** [comment]
LGTM 🚀

**Pull request merged**
