### PR TITLE
add pipeline to build RC from staging branch

### PR DESCRIPTION
**Pull request by gandlafbtc**
# Fixes: Adding pipeline to automatically create RC from staging branch

## Changes

- Add GH action

## PR Tasks

- [x] Open PR
- [x] run `npm run test` --> no failing unit tests
- [x] run `npm run format`

### CODE REVIEW

**Comment by callebtc** [comment]
Good work, I know too little about NPM to give a good judgement here though :)

**Comment by Egge21M** [comment]
@gandlafbtc great addition! Could you explain the flow for future prereleases?

We would increment the minor version number on development and then merge to staging? We would still have to add a tag ourselves, right?

I wonder if it wouldn't be better if we had version specific branches. That way we could we could work on separate versions at the same time (e.g. current release and version 2.x).

**Comment by gandlafbtc** [comment]
It would automatically create the incremented minor version and create an RC release under the `next` npm tag. I have git tags turned off, but maybe it's better to turn it on, so it's easier to reference? 

I'm open to the idea of version branches, I haven't had too much experience with it though. So you would have to take the lead to structure that @Egge21M

**Review by Egge21M — APPROVED** [review]

**Comment by Egge21M** [comment]
> It would automatically create the incremented minor version and create an RC release under the `next` npm tag. I have git tags turned off, but maybe it's better to turn it on, so it's easier to reference?

Awesome! I was not aware that `version prerelease` would automatically bump to the next minor version. I think having automatic git tags could be very helpful. Ideally we would come up with a system where a merge to a branch kicks of the whole release, and tags are part of that IMO.

> I'm open to the idea of version branches, I haven't had too much experience with it though. So you would have to take the lead to structure that @Egge21M

Happy to do that. Lets get this one merge first, and discuss the best way forward in a different PR. I have put this on my list and will propose something next week.

**Pull request merged**
