### PR TITLE
fix melt response bug

### PR DESCRIPTION
**Pull request by gandlafbtc**
While testing the new release version with nutstash, i encountered a bug when trying to melt. The issue is, that the preimage might be null sometimes, and if that's the case, we get a 'bad response', eventhough the payment went through.

### CODE REVIEW

**Comment by gandlafbtc** [comment]
@BilligsterUser

**Comment by BilligsterUser** [comment]
do you know why the preimage is null?

**Comment by gandlafbtc** [comment]
i think because some LNbits backends don't provide it.
At least that's what i remember from asking @callebtc

**Comment by BilligsterUser** [comment]
then we should update the type

```typescript
export type MeltResponse = {
	paid: boolean;
	preimage: string|null;
	change?: Array<SerializedBlindedSignature>;
} & ApiError;
```

**Pull request merged**
