### PR TITLE
Remove payLnInvoice helper

### PR DESCRIPTION
**Pull request by Egge21M**
## Description

This PR removes the payLnInvoice helper function. Instead people should just use `createMeltQuote` and `meltProofs` to pay Lightning invoices.

## Changes

- Removes `payLnInvoice`

## PR Tasks

- [x] Open PR
- [x] run `npm run test` --> no failing unit tests
- [x] run `npm run format`

### CODE REVIEW

**Comment by Egge21M** [comment]
> Impossible to review due to history.

Changed target to `fees-and-coinselection` for clear history until that is ready to merge

**Comment by gandlafbtc** [comment]
looks good, merging it into calle's PR

**Comment by Egge21M** [comment]
> looks good, merging it into calle's PR

Thanks! Should probably have marked it as draft until the fee PR is merged.
I think we should not merge into a branch that is under review, as reviewers will now see these changes in calle's PR as well, although they already have been reviewed.

**Comment by gandlafbtc** [comment]
Agree :grinning: reviewed the PR, saw ready to merge and pulled the trigger.  But yeah, let's not do that in the future

**Pull request merged**
